#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_ROOT="${SIYU_SKILLS_SOURCE_ROOT:-$ROOT_DIR/plugins}"
OUT_DIR="${1:-$ROOT_DIR/dist/skills}"

if [[ -z "$OUT_DIR" || "$OUT_DIR" == "/" || "$OUT_DIR" == "$ROOT_DIR" ]]; then
  echo "error: unsafe output directory: $OUT_DIR" >&2
  exit 2
fi
if [[ ! -d "$SOURCE_ROOT" ]]; then
  echo "error: source directory does not exist: $SOURCE_ROOT" >&2
  exit 2
fi

python3 - "$SOURCE_ROOT" "$OUT_DIR" "$ROOT_DIR/VERSION" <<'PY'
from __future__ import annotations
import json
from pathlib import Path
import re
import shutil
import sys

source, output, version_file = map(Path, sys.argv[1:])
if output.exists():
    if not (output / ".siyu-build-output").is_file():
        raise SystemExit(f"refusing to replace unmarked directory: {output}")
    shutil.rmtree(output)
output.mkdir(parents=True)
(output / ".siyu-build-output").write_text("generated by tools/build_skills.sh\n", encoding="utf-8")

included, skipped = [], []
for skill_md in sorted(source.rglob("SKILL.md")):
    skill_dir = skill_md.parent
    name = skill_dir.name
    text = skill_md.read_text(encoding="utf-8")
    frontmatter = text.split("---", 2)[1] if text.startswith("---") and text.count("---") >= 2 else ""
    beta = "beta" in name.casefold() or bool(re.search(r"(?mi)^beta:\s*true\s*$", frontmatter))
    if beta:
        skipped.append(name)
        continue
    target = output / name
    if target.exists():
        raise SystemExit(f"duplicate skill directory name: {name}")
    shutil.copytree(skill_dir, target, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"))
    included.append(name)

manifest = {
    "version": version_file.read_text(encoding="utf-8").strip(),
    "included": included,
    "skipped_beta": skipped,
}
(output / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"built {len(included)} skills -> {output}")
if skipped:
    print("skipped beta:", ", ".join(skipped))
PY
